title: ENSPY AI MENTORING
description: "\"For tomorrow belongs to the people who prepare for it today.\" - African Proverb"
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

