title: ENSPY AI MENTORING
description: "\"Machine intelligence is the last invention that humanity will ever need to make.\"\n\nNick Bostrom"
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman